config/routes.rb
require 'resque/server'

Uccloud::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, encryptor: :plain

     resources :accounts do
       collection do
         get 'my_access_code', as: 'my_access_code'
         get 'advantages', as: 'advantages'
         get 'join', as: 'join'
         get 'faq', as: 'faq'
         post 'change_access_code'
         post 'change_email'
         post 'add_email'
       end
     end

  root :to => 'accounts#my_access_code'

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :admin_email, :description, :disabled, :name
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/email_address.rb
class EmailAddress < ActiveRecord::Base
  belongs_to :user
  attr_accessible :email, :primary
end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
  belongs_to :session
  belongs_to :user
  attr_accessible :host, :user_id
end

app/models/mail_parser.rb
require 'mail'

class MailParser

  def self.perform(raw)
    mail = Mail.new(raw)

    Rails.logger.debug "Host: #{mail.from}"
    Rails.logger.debug "Invitees: #{mail.to}"
    Rails.logger.debug "CC(Account): #{mail.cc}"
    Rails.logger.debug raw

    new_users = []

    unless EmailAddress.where(email: mail.from.first.downcase).exists?
      new_users << User.create(email: mail.from.first.downcase)
    end

    mail.to.each do |email|
      unless EmailAddress.where(email: email.downcase).exists?
        new_users << User.create(email: email.downcase)
      end
    end

    new_users.each { |u| u.reset_authentication_token! }

    create_session(mail, new_users)
  end

  def self.create_session(mail, new_users)
    calendar = scheduled_meeting?(mail)
    create_ad_hoc_session(mail, new_user) unless calendar

    if calendar && !calendar.events.empty?
      Rails.logger.debug "Creating scheduled session"
      start_datetime = calendar.events.first.start_time
      end_datetime = calendar.events.first.finish_time

      host = User.where(email: mail.from.first.downcase).first
      ot_session = OTSDK.create_session("localhost")
      session = Session.create(host_id: host.id, scheduled_session: true, start_datetime: start_datetime, end_datetime: end_datetime, subject: mail.subject, message_body: mail.body, ot_session_id: ot_session.session_id)

      session.invitees << Invitee.new(host: true, user_id: host.id)
      mail.to.each do |email|
        user = EmailAddress.where(email: email.downcase).first.user
        session.users << user
      end

      users = session.users - new_users
      users.each do |user|
        email = RecognizedInvitee.send_invitation(session, user)
        email.deliver
      end
      new_users.each do |user|
        email = UnrecognizedInvitee.send_invitation(session, user)
        email.deliver
      end
    end
  end

  def self.scheduled_meeting?(mail)
    mail.attachments.each do |attm|
      return RiCal.parse_string(attm.decoded).first if attm.filename == "invite.ics" # Google Calendar Invite
    end
    mail.parts.each do |part|
      return RiCal.parse_string(part.body.decoded).first if part.mime_type == "text/calendar" # MS Outlook Invite
    end

    nil
  end

  def self.create_ad_hoc_session(mail, new_users)
    Rails.logger.debug "Creating ad hoc session"
    host = User.where(email: mail.from.first.downcase).first
    ot_session = OTSDK.create_session("localhost")

    session = Session.create(host_id: host.id, scheduled_session: false, start_datetime: Time.now, end_datetime: Time.now + 2.hours, subject: mail.subject, message_body: mail.body, ot_session_id: ot_session.session_id)

    session.invitees << Invitee.new(host: true, user_id: host.id)
    mail.to.each do |email|
      user = EmailAddress.where(email: email.downcase).first.user
      session.users << user
    end

    users = session.users - new_users
    users.each do |user|
      email = RecognizedInvitee.send_invitation(session, user)
      email.deliver
    end
    new_users.each do |user|
      email = UnrecognizedInvitee.send_invitation(session, user)
      email.deliver
    end
  end

end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :account
  belongs_to :host, class_name: User
  has_many :invitees
  has_many :users, :through => :invitees
  attr_accessible :subject, :host_id, :start_datetime, :end_datetime, :host_id, :scheduled_session, :message_body, :ot_session_id

  def now?
    start_datetime <= Time.zone.now
  end

  scope :scheduled, conditions: {scheduled_session: true}
  scope :on_demand, conditions: {scheduled_session: false}

  scope :active, (lambda do
    now = Time.now.utc
    for_on_demand = "(scheduled_session = 'f' AND start_datetime >= ?)"
    for_scheduled = "(scheduled_session = 't' AND start_datetime <= ? AND end_datetime >= ?)"
    {conditions: ["#{for_on_demand} OR #{for_scheduled}", now - 3.hours, now + 30.minutes, now - 1.hour], order: :start_datetime}
  end)

end

app/models/user.rb
require Rails.root.join('lib', 'devise', 'encryptors', 'plain')

class User < ActiveRecord::Base
  belongs_to :account
  has_many :email_addresses, :dependent => :delete_all
  has_many :invitees
  has_many :sessions, :through => :invitees
  attr_accessible :custom_access_code, :display_name, :host_privileges, :time_zone, :user_access_code, :email

  devise :database_authenticatable, :registerable, :token_authenticatable, :encryptable, :encryptor => :plain

  validates_uniqueness_of :email
  validates_uniqueness_of :user_access_code

  validates_presence_of :email, :on => :create, :message => "can't be blank"
  validates_presence_of :user_access_code, :on => :create, :message => "can't be blank"

  before_validation(:on => :create) do
    # WARNING: Quick and dirty implementation
    last = User.where("user_access_code like '555-555-%'").order(:user_access_code).last

    # TODO only 10000 users for prototype and is flawed as it can break uniqueness of user_access_code
    if last
      num = last.user_access_code.split("-")[2].to_i + 1
      self.user_access_code = "555-555-#{'%04d' % num}"
    else
      self.user_access_code = "555-555-" + ("%04d" % User.count)
    end
  end

  after_create() do
    self.email_addresses.create(email: self.email, primary: true)
    self.reset_authentication_token!
  end

  def encrypted_password
    user_access_code
  end

  def encrypted_password=(pass)
     user_access_code = pass
  end

  def password
     user_access_code
  end

  def password=(pass)
     user_access_code = pass
  end

  def password_salt
    'no salt'
  end

  def password_salt=(new_salt)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!, except: [:advantages]

  def my_access_code

  end

  def advantages

  end

  def join
    @sessions = current_user.sessions.active
    @session = @sessions.last
    if @session && @session.ot_session_id
      @session_id = @session.ot_session_id
    else
      @session_id = "2_MX4yMTg0MjQ1Mn5-VHVlIERlYyAwNCAxMjowMzo0MyBQU1QgMjAxMn4wLjcxNjA3NDc2fg"
    end
  end

  def faq

  end

  def change_access_code
    @user = current_user
    @user.user_access_code = params[:user][:user_access_code]
    @user.custom_access_code = true
    @user.save

    redirect_to action: 'my_access_code'
  end

  def change_email
    @user = current_user

    if params[:delete]
      params[:emails].each do |email_id|
        EmailAddress.find(email_id).destroy
      end
    elsif params[:primary]
      email_id = params[:emails].first
      email = EmailAddress.find(email_id)
      @user.email_addresses.each {|e| e.update_attributes(primary: false)}
      email.update_attributes(primary: true)
      @user.update_attributes(email: email.email)
    end

    redirect_to action: 'my_access_code'
  end

  def add_email
    @user = current_user
    @user.email_addresses.create(email: params[:email]) unless params[:email].blank?

    redirect_to action: 'my_access_code'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    if params[:auth_token]
      "/accounts/join"
    else
      root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/advantages.html.slim
.advantages_left
  .box

    h1 Collaborate Universally

    ul
      li Collaborate with anyone -- in or outside of your organization
      li No need for any specialized hardware or software

  .box
    h1 Get Started Effortlessly

    ul
      li No IT effort required – seamlessly works with your existing applications

      li No new hardware or software installation required

.advantages_right

  .box
    h1 Intuitively Easy to Use

    ul
      li No new applications – just schedule like always using your existing calendar
      li Never worry about remembering someone else’s conference codes

  .box
    h1 True Enterprise-grade

    ul
      li True enterprise-grade video and audio quality
      li Secure collaboration – only invited attendees can join a session

app/views/accounts/faq.html.slim
#faq
  h3 How do I schedule a UC Cloud video collaboration session?
  div Simply cc &quot;&lt;your company name&gt;@uccld.com&quot; to your calendar invites -- you and your guests will immediately receive emailed instructions on how to easily connect to the UC Cloud video collaboration session.


  h3 How do I start an impromptu UC Cloud video collaboration session?
  div Simply cc &quot;&lt;your company name&gt;@uccld.com&quot; in an email to your desired collaborators, and all invited will immediately receive emailed instructions on how to easily connect to that UC Cloud video collaboration session.


  h3 How do I join a UC Cloud video collaboration session?
  div
    | You have several options to meet all your possible needs:
    | If you already have H.323 standards base video equipment you can easily connect by dialing uccld.com and entering your personal access code when prompted, or you can simply dial &lt;your_access_code&gt;@uccld.com ;
    | On a Mac or PC you can easily connect via a browser by clicking on the provided URL link in the invitation email;
    | You can also simply call into a session, without video, by dialing (408) UCCLOUD (408-822-5683) and entering your personal access code.


  h3 How do I set my personal access code?
  div To customize or reset your personal access code please click here.


  h3 Why would I want to set my own personal access code?
  div Your personal access code is all you have to remember to join any UC Cloud video collaboration session to which you&#x27;ve been invited -- you will never have to fumble around for someone else&#x27;s conference codes again!  As such, make it easy to remember and you will never waste time again trying to collaborate.  (And no, you don&#x27;t have to share it with anyone -- everyone gets their own personal access code, even first time users.)


  h3 How do I connect from a shared H.323 endpoint (e.g., a conference room system)?
  div From H.323 standards base video equipment you can easily connect by dialing uccld.com and entering your personal access code when prompted, or you can simply dial &lt;your_access_code&gt;@uccld.com .   You will probably find it convenient to configure a UC Cloud speed dial pointing to uccld.com .


  h3 How do I connect from a personal (dedicated) endpoint?
  div From H.323 standards base video equipment you can easily connect by dialing uccld.com and entering your personal access code when prompted, or you can simply dial &lt;your_access_code&gt;@uccld.com .  You will probably find it convenient to configure a UC Cloud speed dial pointing to &lt;your_access_codediv@uccld.com if you are the only user of that equipment.


  h3 How do I pre-register a personal (dedicated) endpoint?
  div Configure a UC Cloud speed dial pointing to &lt;your_access_codediv@uccld.com (if you are the only user of that equipment).


  h3 Why would I want to pre-register a personal (dedicated) endpoint?
  div It will make it quicker to join any UC Cloud video collaboration sessions.


  h3 How do I download a software video endpoint for my PC or tablet?
  div Please click here.


  Can I really sign up for a FREE 30 day trial of UC Cloud?
  div Absolutely - please click here to do so!


  h3 Will my email address be used for anything outside of enabling UC Cloud video collaboration sessions?
  div No -- we only use your email address for making video collaboration easy and convenient!

javascript:
  $(function() {
          $( "#faq" ).accordion();
      });

app/views/accounts/join.html.slim
#users
  .header Session Participants

- if @session && @session.ot_session_id

  h3 = @session.subject

  p To join your session click the connect button

- else

  p To join a demo session click the connect button


#videobox

button#connect CONNECT TO SESSION

javascript:
  var apiKey = #{API_KEY};
  var sessionId = "#{@session_id}";

  var session;

  TB.addEventListener('exception', exceptionHandler);
  session = TB.initSession(sessionId);

  //Video chat event listeners
  session.addEventListener('sessionConnected', sessionConnectedHandler);
  session.addEventListener('streamCreated', streamCreatedHandler);
  session.addEventListener('streamDestroyed', streamDestroyedHandler);

  $(function () {
    $("#connect").click (function (e) {
      if (e.target.innerText === "CONNECT TO SESSION") {
        //TODO: Generate token with javascript.
        var token = '#{OTSDK.generate_token(session_id: @session_id, role: OpenTok::RoleConstants::PUBLISHER, connection_data: "{\"email\": \"#{current_user.email}\"}")}';
        session.connect(apiKey, token);
        e.target.innerText = "DISCONNECT";
      } else {
        session.disconnect();
        e.target.innerText = "CONNECT TO SESSION";
      }

    });
  });

app/views/accounts/my_access_code.html.slim
.first
  h1 1. Enter your email addresses.
  div.bordered_form
    = form_tag(change_email_accounts_path, method: "post") do
      table.emails
        - current_user.email_addresses.each do |email|
          tr
            td = check_box_tag :"emails[]", email.id, false, disabled: email.primary
            td
              = email.email
              - if email.primary
                b
                  |  (PRIMARY)

      div.buttons
        = submit_tag "SET AS PRIMARY", name: 'primary'
        = submit_tag "DELETE", name: 'delete'
        = submit_tag "ADD NEW", id: 'new'

  div
    p Add any email addresses or aliases with which you would like to be reachable for video collaboration sessions.
    p
      b Note:
      | Your email addresses are used only for making video collaboration sessions easier – click to see our privacy policy

    #new_email_dialog*{style: "display: none", title: "Add new email"}
      = form_tag(add_email_accounts_path, method: "post") do
        = text_field_tag :email
        div
          = submit_tag "Add"

    javascript:
      $(function() {
        $( "#new" ).click(function() {
          $( "#new_email_dialog" ).dialog();
          return false;
        });
      });

.second

  h1 2. Set your personal access code.
  div.bordered_form
    = form_for(current_user, as: "user", url: change_access_code_accounts_path, method: 'post') do |f|
      = f.label :user_access_code, "My access code:"
      = f.text_field :user_access_code

      div.buttons
        = f.submit "Save & Update"
  div
    | Personal access codes must be 10 digit numbers.
    br
    | Tip: Choose a personal access code that is easy to remember – for example, one of your phone numbers.

javascript:
  $(function() {
    $("#user_user_access_code").mask("999-999-9999")
  });

app/views/common/_tabs.html.slim
ul
  li *{class: current_page?(controller: "/accounts", action: "advantages") ? "active" : ""}
    = link_to "Advantages", advantages_accounts_path
  - if current_user
    li *{class: current_page?(controller: "/accounts", action: "join") ? "active" : ""}
      = link_to "Join a Session", join_accounts_path
    li *{class: current_page?(controller: "/accounts", action: "my_access_code") || current_page?("/") ? "active" : ""}
      = link_to "My Access Info", my_access_code_accounts_path
    li *{class: current_page?(controller: "/accounts", action: "faq") ? "active" : ""}
      = link_to "FAQ", faq_accounts_path
  - else
    li *{class: current_page?(controller: "devise/sessions", action: "new") ? "active" : ""}
      = link_to "Log in", new_user_session_path
    li *{class: current_page?(controller: "devise/registrations", action: "new") ? "active" : ""}
      = link_to "Sign Up", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title UC Cloud - next generation Video Collaboration
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "http://static.opentok.com/v1.1/js/TB.min.js"
    = csrf_meta_tags

  body
    section.main
      header
        - if current_user
          .logout
            = link_to("Contact Us", "#")
          .logout
            = link_to("Log out", destroy_user_session_path, :method => :delete)
        = image_tag "logo.png"
        .description On-demand Enterprise-Grade Video Collaboration – Anyone, Anywhere, Anytime
      section
        nav
          = render :partial => "common/tabs"
        .content
          = yield
      footer
       - if current_user
        .powered
          = image_tag "powered.png"
        .copyright &copy; 2012, POLYCOM, INC
       - else
        .copyright &copy; 2012, UC CLOUD

app/views/recognized_invitee/send_invitation.html.slim
p <i><strong>Congratulations</strong></i> - #{@session.host.email} has invited you to an UC Cloud video collaboration session!

p It is scheduled to start #{@session.now? ? 'now' : l(@session.start_datetime, format: :email)}. You can easily join this session by either:

ol
  li <strong>On a personal computer</strong> <a href="#{new_user_session_url}?auth_token=#{@user.authentication_token}">click this link</a> to join from a browser.
  li If you have a <strong>standards based video endpoint</strong> dial the UC Cloud speed dial (“uccld.com”) and enter your personal access code.
  li If you’d like to <strong>simply call into this session</strong> (without video), please dial (408) UCCLOUD (408-822-5683) and enter your personal access code.
br
br
h2 Helpful Links:
p To customize or reset your personal access code please <a href="#{my_access_code_accounts_url}">click here</a>. (Why is this useful?)

p To download a software video endpoint for your PC or tablet please <a href="#">click here</a>. (Why is this useful?)

p To pre-register an endpoint please <a href="#">click here</a>. (Why is this useful?)

p To schedule your own UC Cloud video collaboration sessions please <a href="#">click here</a> for a free 30 day trial.
br
br
h2 About:
p UC Cloud provides on-demand enterprise-grade video collaboration, enabling you to painlessly collaborate with anyone, anywhere, anytime.
p UC Cloud is powered by Polycom, the leading provider of enterprise-grade video collaboration technology.
p For more information, please contact us at <a href="mailto:info@uccld.com">info@uccld.com</a>.

app/views/recognized_invitee/send_invitation.text.erb
Congratulations - <%= @session.host.email %> has invited you to an UC Cloud video collaboration session!

It is scheduled to start <%= @session.now? ? 'now' : @session.start_datetime %>. You can easily join this session by either:

1. On a personal computer click this link to join from a browser <%= "#{new_user_session_url}?auth_token=#{@user.authentication_token}" %> .

2. If you have a standards based video endpoint dial the UC Cloud speed dial (“uccld.com”) and enter your personal access code.

3. If you’d like to simply call into this session (without video), please dial (408) UCCLOUD (408-822-5683) and enter your personal access code.


~ Helpful Links: ~
To customize or reset your personal access code please click here. (For more information click Why is this useful?) 

To download a software video endpoint for your PC or tablet please click here. (For more information click Why is this useful?)  

To pre-register an endpoint please click here. (For more information click Why is this useful?) 

To schedule your own UC Cloud video collaboration sessions please click here for a free 30 day trial.


<% if false && @session.message_body -%>
~ Original invitation: ~
<%= @session.message_body %>


<% end -%>
~ About: ~
UC Cloud provides on-demand enterprise-grade video collaboration, enabling you to painlessly collaborate with anyone, anywhere, anytime.

UC Cloud is powered by Polycom, the leading provider of enterprise-grade video collaboration technology.  

For more information, please contact us at info@uccld.com.

app/views/unrecognized_invitee/send_invitation.html.slim
p <i><strong>Congratulations</strong></i> - #{@session.host.email} has invited you to an UC Cloud video collaboration session!

p It is scheduled to start #{@session.now? ? 'now' : l(@session.start_datetime, format: :email)}. You can easily join this session by either:

ol
  li <strong>On a personal computer</strong> <a href="#{new_user_session_url}?auth_token=#{@user.authentication_token}">click this link</a> to join from a browser.
  li If you have a <strong>standards based video endpoint</strong> dial the UC Cloud speed dial (“uccld.com”) and enter your personal access code, which has been temporarily set to #{@user.user_access_code}.
  li If you’d like to <strong>simply call into this session</strong> (without video), please dial (408) UCCLOUD (408-822-5683) and enter your personal access code, which has been temporarily set to #{@user.user_access_code}.
br
br
h2 Helpful Links:
p To customize or reset your personal access code please <a href="#{my_access_code_accounts_url}">click here</a>. (Why is this useful?) 

p To download a software video endpoint for your PC or tablet please <a href="#">click here</a>. (Why is this useful?)  

p To pre-register an endpoint please <a href="#">click here</a>. (Why is this useful?) 

p To schedule your own UC Cloud video collaboration sessions please <a href="#">click here</a> for a free 30 day trial.
br
br
h2 About:
p UC Cloud provides on-demand enterprise-grade video collaboration, enabling you to painlessly collaborate with anyone, anywhere, anytime.
p UC Cloud is powered by Polycom, the leading provider of enterprise-grade video collaboration technology.  
p For more information, please contact us at <a href="mailto:info@uccld.com">info@uccld.com</a>.

app/views/unrecognized_invitee/send_invitation.text.erb
Congratulations - <%= @session.host.email %> has invited you to an UC Cloud video collaboration session!

It is scheduled to start <%= @session.now? ? 'now' : @session.start_datetime %>. You can easily join this session by either:

1. On a personal computer click this link to join from a browser <%= "#{new_user_session_url}?auth_token=#{@user.authentication_token}" %>.

2. If you have a standards based video endpoint dial the UC Cloud speed dial (“uccld.com”) and enter your personal access code, which has been temporarily set to <%= @user.user_access_code %>.

3. If you’d like to simply call into this session (without video), please dial (408) UCCLOUD (408-822-5683) and enter your personal access code, which has been temporarily set to <%= @user.user_access_code %>.


~ Helpful Links: ~
To customize or reset your personal access code please click here. (For more information click Why is this useful?) 

To download a software video endpoint for your PC or tablet please click here. (For more information click Why is this useful?)  

To pre-register an endpoint please click here. (For more information click Why is this useful?) 

To schedule your own UC Cloud video collaboration sessions please click here for a free 30 day trial.


<% if false && @session.message_body -%>
~ Original invitation: ~
<%= @session.message_body %>


<% end -%>
~ About: ~
UC Cloud provides on-demand enterprise-grade video collaboration, enabling you to painlessly collaborate with anyone, anywhere, anytime.

UC Cloud is powered by Polycom, the leading provider of enterprise-grade video collaboration technology.  

For more information, please contact us at info@uccld.com.